
[general]

	[general.lightning]
		hide_lightning = false

	[general.price_info]
		item_value_lore = true
		item_price_lore = true

	[general.chat_replacer]
		chat_editor = true

	[general.reparty]
		delay = 500
		auto_reparty = false
		rejoin_reparty = false

	[general.third_person]
		hide_crosshair_in_third_person = true

	[general.etherwarp]
		etherwarp_overlay = false
		only_show_when_sneaking = true
		overlay_color = "255,0,255,0"
		sync_with_server = false
		invalid_teleport_color = "255,255,0,0"
		show_fail_location = false
		highlight_type = 0

	[general.damage_numbers]
		hide_gray_numbers = true
		hide_enchants_damage = true

	[general.0_health_nametags]
		hide_0_health_nametags = true

	[general.death_animation]
		no_death_animation = false

	[general.messages]
		block_useless_messages = true

	[general.toggle_sprint]
		toggle_sprint_overlay = false
		toggle_sprint = false
		sprinting_enabled_text = ""

	[general.party]
		auto_transfer = false

	[general.gyro]
		gyro_radius = false

	[general.falling_blocks]
		hide_falling_blocks = false

[party_finder]

	[party_finder.buttons]
		better_party_finder_message = false

	[party_finder.stats]
		"auto_/ds" = false
		"auto_/ds_party" = false
		"advanced_/ds_and_//kuudra" = false

	[party_finder.auto_kicker]
		recent_kick = false
		kick_classes = false
		kick_everyone = false
		auto_kick = false
		classes_to_kick = "Tank, Healer"
		minimum_secrets = "3000"

[dungeons]

	[dungeons.run_overview]
		run_overview = false

	[dungeons.crystal]
		crystal_timer = false

	[dungeons.dungeon_end_stats]
		custom_end_info = false

	[dungeons.run_splits]
		run_splits = false

	[dungeons.terminals]
		terminal_splits = false
		terminal_timer = true
		terminal_tracker = false

	[dungeons.qol]
		show_secret_clicks = false
		secret_click_color = "255,0,255,0"
		only_self = true
		blood_camp_timer = false
		hide_blessing_messages = false
		"auto_architect's_first_draft" = true

	[dungeons.soulweaver_gloves]
		hide_soulweaver_skulls = true

	[dungeons.spirit_leap]
		spirit_leap_names = false

	[dungeons.blaze]
		blaze_timer = true

	[dungeons.mort]
		disable_mort_messages = false

	[dungeons.cooldown]
		dungeon_warp_cooldown = false

	[dungeons.player_logs]
		player_logging = false

	[dungeons.rng_meter]
		"&dbackground" = true
		"&dwarn_when_close" = true
		"&dpost-run_only" = true
		"&dremaining_score_alert" = 1200
		"&drng_meter" = false

	[dungeons.puzzle_timers]
		water_board_timer = false

[dungeon_chest_profit]
	dungeon_chest_profit = false

	[dungeon_chest_profit.customizing]
		show_background = true

[gui]

	[gui.speed_display]
		speed_display = true

	[gui.new_year_cakes]
		cake_numbers = true

	[gui.stack_tracker]
		stack_tracker = false

	[gui.container_value]
		container_value = false
		book_craft_value = false

	[gui.crystal_hollows]
		crystal_hollows_map = false

	[gui.cells_align]
		cells_align_timer = false

	[gui.item_value]
		item_value_overlay = false

	[gui.party]
		party_list_overlay = false

[terminals]
	hide_terminal_tooltips = true
	block_wrong_clicks = false
	"don't_pickup_items" = false
	hide_wrong_items = true

	[terminals.terminal_solvers]
		colors_solver = false
		starts_with_solver = false
		rubix_terminal_solver = false
		"&aterminal_solvers" = false
		numbers_solver = false

[solvers]

	[solvers.blaze_solver]
		blaze_solver = true
		line_to_next_blaze = true
		blaze_lines = 2

	[solvers.teleport_maze]
		teleport_maze_solver = false

	[solvers.three_weirdos]
		three_weirdos_solver = false

	[solvers.livid]
		livid_solver = true
		hide_wrong_livids = true

	[solvers.trivia]
		trivia_solver = false

	[solvers.simon_says]
		simon_says_style = 0
		cancel_incorrect_clicks = true
		simon_says_solver = true

	[solvers.arrow_align]
		invert_sneak = true
		block_arrow_align_clicks = true
		arrow_align_solver = true

	[solvers.dojo]
		mastery = false

