
[partycommands]
	msg = false
	allowed_players = ""
	help = true
	fun_blacklist = ""
	fact = true
	morse = true
	cat = true
	command_blacklist = ""
	calc = true
	dog = true
	fun_commands = false

[reparty]
	cooldown = 15
	enable_autojoin = false

[trophyfish]
	enable_trophyfish = false

[dungeons]
	device_notification = false
	relevant_items = "scylla,hyperion,astraea,valkyrie,terminator,juju,axe of the shredded,livid dagger,spirit bow,last breath"
	show_ender_dragon = false
	send_i4_fail_message = ""
	enable_kuudra = false
	notify_i4_status = false
	send_i4_message = ""
	waypoint_beacon = false
	device_notification_only_for_self = false
	enable_dpu = false
	i4_done_text = "&a&l4th Device is done! (i4)"
	i4_failed_text = "&c&l4th Device is not done! (i4)"
	show_equipment = true
	terms_overview = false
	terminal_waypoints = false
	send_complete_message = ""

[bridge]
	bridge_bot = "bridgebot"
	guild_formatting = "&2Bridge > &6<1>: &r<2>"
	officer_formatting = "&3Bridge > &6<1>: &r<2>"

[replaceghost]
	enable_replaceghost = false
	message = "and skillissued too much"
	ghostnames = ""

[fragbot]
	owner = ""
	enable_fragbot = false
	bot = ""
	whitelist = ""

[misc]
	mania_performance_mode = false
	wither_hitbox_type = 0
	vamp_all_hit = false
	wither_hitbox = false
	vamp_slayer_mania_fix = false
	wither_hitbox_color = "255,186,0,255"
	vamp_splits = false
	autopet_notification = false
	mania_debug_mode = false
	spring_boots_height_display = false
	spring_boots_edit_mode = false

