
[general]

	[general.guis]
		bobber_overlay = false
		legion_overlay = false

	[general.waypoints]
		detect_patcher_cords = false
		hide_own_waypoints = 0

[partyfinder]
	auto_invite_for_partyfinder = true

[debug]
	test_features = false
	always_diana_mayor = false
	always_in_skyblock = false

[kuudra]
	attribute_value_overlay = false
	select_displayed_lines = 0
	kuudra_key_discount = false
	bazaar_setting_kuudra = 0
	key_price = 0
	attribute_shards_for_chest_profit = false
	max_displayed_items = 15
	kuudra_pet_level = "100"
	kuudra_pet_rarity = 0

[customization]

	[customization.sound_settings]
		"shelmet,_plushie_and_remedies_drop_volume" = 50
		inquisitor_spawn_volume = 100
		daedalus_stick_drop_sound = ""
		burrow_spawn_sound = ""
		chimera_drop_sound = ""
		test_property_sound = 0
		inquisitor_spawn_sound = "expOrb"
		daedalus_stick_drop_volume = 50
		achievement_sound_volume = 50
		burrow_spawn_volume = 50
		relic_drop_volume = 50
		test_property_sound_volume = 50
		relic_drop_sound = ""
		chimera_drop_volume = 50
		"shelmet,_plushie_and_remedies_drop_sound" = "mfsound"

	[customization.colors]
		guess_color = "255,255,255,255"
		treasure_burrow_color = "255,255,170,0"
		start_burrow_color = "255,85,255,85"
		mob_burrow_color = "255,255,85,85"
		slot_highlighting_color = "255,255,0,0"

[mining]
	highlight_all_possible_fossils = false
	speed_boost_title = false
	fossil_solver = false
	fossil_overlay = false
	create_exit_waypoint = false

[diana]

	[diana.diana_waypoint_lines]
		inquis_line = true
		line_width = 1
		burrow_line = false
		guess_line = true

	[diana.diana_waypoints]
		inq_warp_key = true
		remove_guess = false
		all_waypoints_are_inqs = false
		detect_inq_cords = true
		distance_for_remove = 10

	[diana.other]
		add_warps = 3
		custom_chim_message_text = "&6[SBO] &6&lRARE DROP! &d&lChimera! &b{mf} &b#{amount}"
		add_dark_auction_warp = true
		highlight_inquis = true
		share_inquisitor = true
		"inquis/lootshare_color" = "153,0,230,255"
		chim_message = false
		mythos_hp = false
		add_stonks_warp = true
		inquis_lootshare_circle = true
		inquis_lootshare_cylinder = false

	[diana.loot_announcer]
		rare_drop_announcer = true
		show_price_title = true
		loot_screen_announcer = true
		loot_party_announcer = true

	[diana.diana_tracker]
		avg_magic_find_tracker = true
		mob_view = 2
		bazaar_setting_diana = 1
		loot_view = 2
		stats_message = false
		diana_stats = true
		diana_tracker = true
		four-eyed_fish = false

	[diana.diana_burrows]
		diana_burrow_detect = false
		burrow_guess_alternative = true
		dont_warp_if_a_burrow_is_nearby = false
		diana_burrow_guess = false
		diana_burrow_warp = true
		warp_block_difference = "10"

	[diana.inqmessage]
		send_text_on_inq_spawn = ""

[party_commands]

	[party_commands.party_commands]
		ask_carrot = false
		"promote/demote" = false
		check_tps = false
		time_check = false
		warp_party = false
		allinvite = false
		party_transfer = false
		diana_party_commands = true
		party_commands = true

[quality_of_life]
	hide_radio_weak_message = false
	hide_autopet_messages = false
	copy_chat_message = false
	hide_own_flare_when_not_in_range = false
	carnival_redstone_lamp_helper = false
	pickup_log_overlay = false
	carnival_zombie_line = false
	find_dragon_lair = false
	golden_fish_timer = false
	flare_expire_soon_alert = false
	jacob_message_hider = false
	flare_tracker = false
	bridge_bot_name = ""
	hide_sacks_message = false
	copy_rare_drop = false
	hide_tipped_players = false
	carnival_zombie_helper = false
	golden_fish_notification = false
	clean_diana_chat = false
	clickable_messages_to_invite_a_player = false
	formatted_bridge_bot = false

	[quality_of_life.blaze]
		effects_for_blaze = false
		parrot_level = "0"

	[quality_of_life.crown_tracker]
		crown_ghost_mode = false
		crown_tracker = false

